---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-zookeeper-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  authentication:
    type: digest 
    jaasConfig:
     secretRef: credential
  tls:
    secretRef: tls-zookeeper
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-server-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: tls-kafka-internal 
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
        secretRef: tls-kafka-internal
    external:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
        secretRef: tls-kafka-external
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2182
      authentication:
        type: digest
        jaasConfig:
          secretRef: credential
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 2
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-server-connect-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  tls:
    secretRef: tls-connect
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-schema-registry-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  tls:
    secretRef: tls-schemaregistry
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 2
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-ksqldb-server-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  dataVolumeCapacity: 10Gi
  tls:  
   secretRef: tls-ksqldb
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  podTemplate:
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
  image:
    application: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-enterprise-control-center-operator:6.1.0.0
    init: us.gcr.io/wipro-gcp-parsnet-poc/confluent/cp-init-container-operator:6.1.0.0
  dataVolumeCapacity: 10Gi
  authentication:
    type: basic
    basic:
      secretRef: credential
  tls:
    secretRef: tls-controlcenter
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    connect:
      - name: connect
        url:  https://connect.confluent.svc.cluster.local:8083
        tls:
          enabled: true
    ksqldb:
      - name: ksqldb
        url:  https://ksqldb.confluent.svc.cluster.local:8088
        tls:
          enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
